
stages:
  - upload

surge-npx:
  image: node:alpine
  stage: upload
  script:
    - npx surge ./src/www/

deploy-job:
  image: node:alpine
  stage: upload
  script:
    - echo "Application successfully deployed."
